baseURL = 'https://vsvnakers.github.io/'
languageCode = 'zh-cn'
title = 'VSVnakers ä¸»é¡µ'
theme = 'PaperMod'

[pagination]
  pageSize = 10

[params]
    defaultTheme = "auto"
    homeInfoParams = { Title = "ä½ å¥½ï¼Œæˆ‘æ˜¯ VSVNakers ğŸ‘‹", Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸»é¡µï¼šç®€å† / åšå®¢ / æ•™ç¨‹" }

[[menu.main]]
    name = "ç®€å†"
    url = "/resume"
    weight = 1

[[menu.main]]
  name = "åšå®¢"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "æ•™ç¨‹"
  url = "/docs"
  weight = 3
