baseURL = 'https://vsvnakers.github.io/'
languageCode = 'zh-cn'
title = 'VSVnakers ä¸»é¡µ'
theme = 'PaperMod'

[pagination]
  pageSize = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  defaultTheme = "auto"
  homeInfoParams = { Title = "ä½ å¥½ï¼Œæˆ‘æ˜¯ VSVnakers ğŸ‘‹", Content = "æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸»é¡µï¼šä¸ªäºº / åšå®¢ / æ•™ç¨‹ / å­¦ä¹ " }

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/vsvnakers"  

[[menu.main]]
  name = "ğŸ‘¤ ä¸ªäºº"
  url = "/resume"
  weight = 1

[[menu.main]]
  name = "ğŸ“˜ åšå®¢"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "ğŸ“š æ•™ç¨‹"
  url = "/docs"
  weight = 3

[[menu.main]]
  name = "ğŸ“ å­¦ä¹ "
  url = "/study"
  weight = 4

[[menu.main]]
  name = "ğŸ“ æ—¥å¿—"
  url = "/log"
  weight = 4

[[menu.main]]
  name = ""
  url = "https://github.com/vsvnakers"
  weight = 6
  pre = "<img src='/throw/me.png' width='30' style='vertical-align: middle; position: relative; top: 18px;' />"

